version: "3.7"

services:
  web:
    container_name: "QueueManager-api"

    build:
      context: .
      dockerfile: dev.Dockerfile

    volumes:
      - "./src:/home/node/app/src"

    environment:
      DB_URL: mongo-db
      DB_PORT: 27017
      DB_NAME: "qsaas"
      SERVER_PORT: 8072

    depends_on:
      - mongo-db

    ports:
      - "8072:80"

    networks:
      - rabbitmq-net

    command: "npm run dev"

  mongo-db:
    image: mongo

    ports:
      - "27018:27017"

    restart: always

    networks:
      - rabbitmq-net

    volumes:
      - "mongodb:/data/db"

    logging:
      driver: none

volumes:
  mongodb:


networks:
  rabbitmq-net:
    driver: bridge
    name: rabbitmq-net
