version: "3.7"

services:
  node_and_jest:
    container_name: "QueueManager-jest"

    build:
      context: .
      dockerfile: test.Dockerfile
#    volumes:
#    - .:/home/node/app

    environment:
      - SERVER_PORT=8003
      - DB_URL=mongo-db
      - DB_PORT=27017
      - DB_NAME=qsaas_test
      - RABBIT_MQ_URL=amqp://myrabbitmq:5672
      - JWT_KEY=key
      - ENV

    depends_on:
      - mongo-db

    ports:
      - "8003:80"

    command: "npm run test"

  mongo-db:
    image: mongo

    logging:
      driver: none

    ports:
      - "27018:27017"

    restart: "no"
